<?php

namespace App\Services;

use Exception;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class AiDatabaseQueryService
{
    /**
     * Forbidden SQL keywords that are strictly prohibited.
     */
    protected array $forbiddenKeywords = [
        'INSERT',
        'UPDATE',
        'DELETE',
        'DROP',
        'ALTER',
        'TRUNCATE',
        'RENAME',
        'GRANT',
        'REVOKE',
        'EXEC',
        'CREATE',
        'REPLACE',
        'INFORMATION_SCHEMA',
    ];

    /**
     * Validate and execute a SELECT query generated by AI.
     *
     * @param string $sqlQuery
     * @return array
     * @throws Exception
     */
    public function executeSafeQuery(string $sqlQuery): array
    {
        $cleanSql = trim($sqlQuery);

        // Remove trailing semicolon if present
        $cleanSql = rtrim($cleanSql, ';');

        // Check if query starts with SELECT
        if (!preg_match('/^SELECT/i', $cleanSql)) {
            throw new Exception("Hanya query SELECT yang diizinkan untuk keamanan data.");
        }

        // Check for any forbidden keywords
        foreach ($this->forbiddenKeywords as $keyword) {
            if (preg_match('/\b' . $keyword . '\b/i', $cleanSql)) {
                throw new Exception("Operasi SQL '{$keyword}' dilarang demi keamanan database.");
            }
        }

        // Ensure safety limit is applied
        if (!preg_match('/LIMIT\s+\d+/i', $cleanSql)) {
            $cleanSql .= " LIMIT 100";
        }

        try {
            $results = DB::select($cleanSql);
            
            // Convert stdClass array to array of associative arrays
            $data = json_decode(json_encode($results), true);

            return [
                'success' => true,
                'sql'     => $cleanSql,
                'rows'    => count($data),
                'data'    => $data,
            ];
        } catch (Exception $e) {
            Log::error("AiDatabaseQueryService SQL Execution Error: " . $e->getMessage(), [
                'sql' => $cleanSql
            ]);
            throw new Exception("Gagal mengeksekusi query database: " . $e->getMessage());
        }
    }

    /**
     * Extract SQL query from markdown code block ```sql ... ```
     */
    public function extractSqlFromMarkdown(string $text): ?string
    {
        if (preg_match('/```sql\s*(SELECT[\s\S]*?)\s*```/i', $text, $matches)) {
            return trim($matches[1]);
        }

        if (preg_match('/(SELECT[\s\S]*?;)/i', $text, $matches)) {
            return trim($matches[1]);
        }

        return null;
    }
}
